spring:
  datasource:
    url: jdbc:postgresql://database-1.c34saacoeuv8.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

