spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
  profiles:
    active: local
  flyway:
    enabled: true
    locations: db.migration
    cleanDisabled: false

